<div class="row">
    <div class="col-12">

        <p>
            <?= $this->current ?> of <?= $this->pageCount ?>
        </p>

        <nav aria-label="...">
            <ul class="pagination">

                <?php if (isset($this->previous)): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= $this->url(['page' => $this->previous]); ?>"
                           tabindex="-1">Previous</a>
                    </li>
                <?php else: ?>
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                <?php endif; ?>

                <?php foreach ($this->pagesInRange as $key => $page): ?>
                    <li class="page-item <?= $this->current != $page ?: 'active' ?>">
                        <a class="page-link"
                           href="<?= $this->url(['controler' => 'movie', 'action' => 'index', 'page' => $page]) ?>"><?= $page ?></a>
                    </li>
                <?php endforeach; ?>

                <?php if (isset($this->next)): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= $this->url(['page' => $this->next]); ?>">Next</a>
                    </li>
                <?php else: ?>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Next</a>
                    </li>
                <?php endif; ?>

            </ul>
        </nav>
    </div>
</div>