<div class="container">
    <div class="row">

        <div class="col-12">
            <h2><?= $this->movie->title ?></h2>
            <hr>
        </div>

        <div class="col-12" style="margin-bottom: 20px;">
                <a href="<?= $this->url(['controller' => 'movie', 'action' => 'edit', 'id' => $this->movie->id]) ?>"
                   style="width: 55px;" class="btn btn-primary btn-sm">
                    Edytuj
                </a>

            <form style="display: inline-block;" method="post"
                  action="<?= $this->url(['controller' => 'movie', 'action' => 'delete', 'id' => $this->movie->id]) ?>">
                <input type="hidden" name="id" value="<?= $this->movie->id ?>">
                <button type="submit" class="btn btn btn-danger btn-sm" style="width: 55px;" onclick="return confirm('Are you sure?')">Usuń</button>
            </form>
        </div>

        <div class="col-3">
            <img class="img-fluid" src="<?= $this->movie->poster ?>" style="height: 350px;">
        </div>

        <div class="col-9">
            <h3><?= $this->movie->title ?></h3>
            <p><?= $this->movie->description ?></p>
            <p><?= $this->movie->director ?></p>
            <p><?= $this->movie->grade ?></p>
        </div>

    </div>
</div>