<div class="container">
    <div class="row">

        <div class="col-12">
            <h2><?= $this->movie->title ?></h2>
            <hr>
        </div>

        <div class="col-3">
            <img class="img-fluid" src="<?= $this->movie->poster ?>" style="height: 350px;">
        </div>

        <div class="col-9">
            <h3><?= $this->movie->title ?></h3>
            <p><?= $this->movie->description ?></p>
            <p><?= $this->movie->director ?></p>
            <p><?= $this->movie->grade ?></p>
        </div>

    </div>
</div>